/*!CK:3591828555!*//*1418014467,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["ugqdw"]); }

__d("AdsOtherConsts",[],function(a,b,c,d,e,f){e.exports={REACH_TOO_LOW_NUMBER:1000};},null);
__d("List.react",["ReactPropTypes","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=h.createClass({displayName:"List",propTypes:{border:g.oneOf(['none','light','medium','dark']),spacing:g.oneOf(['none','small','medium','large']),direction:g.oneOf(['vertical','horizontal']),valign:g.oneOf(['baseline','top','middle','bottom']),edgepadding:g.bool},getDefaultProps:function(){return {border:'medium',spacing:'medium',direction:'vertical',valign:'top'};},render:function(){var l=this.props.border,m=this.props.direction,n=this.props.spacing,o=m==='horizontal'&&this.props.valign,p,q,r;p=((m==='vertical'?"_4kg":'')+(m==='horizontal'?' '+"_4ki":'')+(o==='top'?' '+"_509-":'')+(o==='middle'?' '+"_509_":'')+(o==='bottom'?' '+"_50a0":''));if(n!=='none'||l!=='none')q=((l==='none'?"_6-i":'')+(l==='light'?' '+"_4ks":'')+(l==='medium'?' '+"_4kt":'')+(l==='dark'?' '+"_4ku":''));if(n!=='none')r=((!this.props.edgepadding?"_6-h":'')+(n==='small'?' '+"_704":'')+(n==='medium'?' '+"_6-j":'')+(n==='large'?' '+"_703":''));var s=j("uiList",p,q,r);return (h.createElement("ul",h.__spread({},this.props,{className:j(this.props.className,s)}),this.props.children));}});e.exports=k;},null);
__d("XUIBlock",["ReactPropTypes","cx"],function(a,b,c,d,e,f,g,h){var i={propTypes:{background:g.oneOf(['base-wash','light-wash','white','highlight','transparent'])},getDefaultProps:function(){return {background:'transparent'};},getBackgroundClass:function(j){var k=((j.background==='base-wash'?"_4-u5":'')+(j.background==='light-wash'?' '+"_57d8":'')+(j.background==='white'?' '+"_4-u8":'')+(j.background==='highlight'?' '+"_4-u7":''));return k;}};e.exports=i;},null);
__d("XUICard.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=g.createClass({displayName:"XUICard",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u2",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("XUICardSection.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=g.createClass({displayName:"XUICardSection",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u3",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("XUIDialogCancelButton.react",["React","XUIDialogButton.react","fbt"],function(a,b,c,d,e,f,g,h,i){var j=g.createClass({displayName:"XUIDialogCancelButton",render:function(){return (g.createElement(h,g.__spread({},this.props,{action:"cancel",label:"Cancel"})));}});e.exports=j;},null);
__d("sliceChildren",["flattenChildren"],function(a,b,c,d,e,f,g){"use strict";function h(i,j,k){if(i==null)return i;var l={},m=g(i),n=0;for(var o in m){if(!m.hasOwnProperty(o))continue;var p=m[o];if(n>=j)l[o]=p;n++;if(k!=null&&n>=k)break;}return l;}e.exports=h;},null);
__d("XUIDialogTitle.react",["LeftRight.react","React","ReactPropTypes","XUICloseButton.react","cx","fbt","sliceChildren","joinClasses"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n){var o=h.createClass({displayName:"XUIDialogTitle",propTypes:{closeButtonText:i.string,showCloseButton:i.bool},getDefaultProps:function(){return {closeButtonText:"Close",showCloseButton:true};},render:function(){var p=null;if(this.props.showCloseButton)p=h.createElement(j,{label:this.props.closeButtonText,className:"layerCancel _51-t"});return (h.createElement("div",h.__spread({},this.props,{className:n(this.props.className,"_4-i0")}),h.createElement(g,null,h.createElement("h3",{className:"_52c9"},m(this.props.children,0,1)),h.createElement("div",{className:"_51-u"},m(this.props.children,1),p))));}});e.exports=o;},null);
__d("ManagedError",[],function(a,b,c,d,e,f){function g(h,i){Error.prototype.constructor.call(this,h);this.message=h;this.innerError=i;}g.prototype=new Error();g.prototype.constructor=g;e.exports=g;},null);
__d("GiftCredits",["AsyncRequest","Dialog","URI"],function(a,b,c,d,e,f,g,h,i){var j={dialog:null,callback:null,purchaseLock:false,purchaseLockExpiryThreshold:5000,purchaseLockTimeoutId:null,getPurchaseCreditPrompt:function(k,l,m,n){j.main(k,null,null,null,m,null,null,null,'BuyCredits',{},n);},redeemGiftcard:function(k,l,m){var n=i(document.location).setPath('/giftcards').toString();j.main(k,null,null,n,null,null,null,null,l,{},m);},getPrompt:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){j.main(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha);},main:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){if(j.isPurchaseLocked())return false;j.setPurchaseLock(true);var ia={_path:'pay',method:'pay',display:'async',app_id:k,receiver:l,api_key:q,credits_purchase:x,action:s,next:n,dev_purchase_params:JSON.stringify(t),additional_params:JSON.stringify(u),order_info:JSON.stringify(m),product:v,package_id:w,request_id:y,sdk:z,quantity:aa,quantity_min:ba,quantity_max:ca,test_currency:da,pricepoint_id:ea,user:fa,user_hash:ga,ingame_gift_data:ha},ja=new g().setURI('/fbml/ajax/dialog/').setData(ia).setMethod('GET').setReadOnly(true).setStatusElement('commerce_get_more_loading');j.callback=o;j.dialog=new h().setAsync(ja).setModal(true).setCloseHandler(function(ka){j.setPurchaseLock(false);o(ka);}).show();},isPurchaseLocked:function(){return j.purchaseLock;},setPurchaseLock:function(k){j.purchaseLock=k;if(k){j.purchaseLockTimeoutId=setTimeout(function(){j.setPurchaseLock(false);},j.purchaseLockExpiryThreshold);}else clearTimeout(j.purchaseLockTimeoutId);return true;}};e.exports=j;},null);
__d("legacy:giftcredits",["GiftCredits"],function(a,b,c,d){a.GiftCredits=b('GiftCredits');},3);
__d("CanvasResizer",["createArrayFromMixed","CSS","DOMEventListener","Vector"],function(a,b,c,d,e,f,g,h,i,j){var k;function l(){var n,o=document.documentElement;if(window.innerHeight){n=window.innerHeight;}else if(o&&o.clientHeight){n=o.clientHeight;}else n=document.body.clientHeight;for(var p=0;p<k.length;p++){var q=k[p];if(!h.hasClass(q,'noresize')){var r=j.getElementPosition(q,'document').y,s=n-r;q.style.height=s/(k.length-p)+'px';}}}i.add(window,'resize',l);var m={smartSizingFrameAdded:function(){k=[];var n=g(document.getElementsByTagName('iframe'));n.forEach(function(o){if(h.hasClass(o,'smart_sizing_iframe')&&!h.hasClass(o,'noresize')){h.removeClass(o,'canvas_iframe_util');k.push(o);}});l();}};e.exports=m;},null);
__d("AssertionError",["ManagedError"],function(a,b,c,d,e,f,g){function h(i){g.prototype.constructor.apply(this,arguments);}h.prototype=new g();h.prototype.constructor=h;e.exports=h;},null);
__d("Assert",["AssertionError","sprintf"],function(a,b,c,d,e,f,g,h){function i(n,o){if(typeof n!=='boolean'||!n)throw new g(o);return n;}function j(n,o,p){var q;if(o===(void 0)){q='undefined';}else if(o===null){q='null';}else{var r=Object.prototype.toString.call(o);q=/\s(\w*)/.exec(r)[1].toLowerCase();}i(n.indexOf(q)!==-1,p||h('Expression is of type %s, not %s',q,n));return o;}function k(n,o,p){i(o instanceof n,p||'Expression not instance of type');return o;}function l(n,o){m['is'+n]=o;m['maybe'+n]=function(p,q){if(p!=null)o(p,q);};}var m={isInstanceOf:k,isTrue:i,isTruthy:function(n,o){return i(!!n,o);},type:j,define:function(n,o){n=n.substring(0,1).toUpperCase()+n.substring(1).toLowerCase();l(n,function(p,q){i(o(p),q);});}};['Array','Boolean','Date','Function','Null','Number','Object','Regexp','String','Undefined'].forEach(function(n){l(n,j.bind(null,n.toLowerCase()));});e.exports=m;},null);